#############################################################################
#
# Project Makefile
#
# (c) Wouter van Ooijen (www.voti.nl) 2016
#
# This file is in the public domain.
# 
#############################################################################

# source files in this project (main.cpp is automatically assumed)
SOURCES := MPU6050.cpp decorator_average.cpp decorator_zero_point.cpp servo.cpp

# header files in this project
HEADERS := accel_meter.h MPU6050.h decorator_average.h decorator_zero_point.h servo.h temp_meter.h gyro_meter.h

# other places to look for files for this project
SEARCH  := 

# set RELATIVE to the next higher directory 
# and defer to the appropriate Makefile.* there
RELATIVE := ..
include $(RELATIVE)/Makefile.due